version: "3.3"
services:
 aria2:
  image: p3terx/aria2-pro
  environment:
   - PUID=${PUID}
   - PGID=${PGID}
   - UMASK_SET=${UMASK_SET}
   - RPC_SECRET=${RPC_SECRET}
   - RPC_PORT=${RPC_PORT}
   - LISTEN_PORT=6888
   - DISK_CACHE=64M
   - IPV6_MODE=false
   - UPDATE_TRACKERS=true
   - CUSTOM_TRACKER_URL=
   - TZ=${TZ}
  volumes:
   - ${HOME}/.config/docker-aria2-pro:/config
   - /mnt/data/downloads:/downloads
  ports:
   - 6800:6800
   - 6888:6888
   - 6888:6888/udp
  restart: unless-stopped

  logging:
   driver: json-file
   options:
    max-size: 1m

 ariang:
  image: superng6/ariang
  ports:
   - 6880:80
  restart: unless-stopped
  logging:
   driver: json-file
   options:
    max-size: 1m
