version: '2'
services:
    plex:
        build: .
        restart: unless-stopped
        network_mode: "host"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./data/config:/config
          - ./data/data:/data
        environment:
          - PLEX_USERNAME=andry_yosua@yahoo.com
          - PLEX_PASSWORD=b$chuwu2w@thuhuvuswuX_#upHadruSp
          - DEBUG=true
