version: "2"
services:
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID
      - PGID
      - TZ
      - MYSQL_ROOT_PASSWORD=yosuadb
    volumes:
      - ~/.config/docker-mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    links:
      - mariadb:db
