---
services:
  mysqld:
    build: ./mysqld
    environment:
     - MYSQL_ROOT_PASSWORD=rootmariadb
     - MYSQL_USER=andry
     - MYSQL_PASSWORD=yosuamariadb
    volumes:
     - /d/Documents/Projects/docker/mysql/data:/var/lib/mysql
    network_mode: "host"
    restart: unless-stopped
  pma:
    build: ./pma
    environment:
     - PMA_HOST=192.168.99.100
     - PMA_PORT=3306
    ports:
     - 8080:80
    volumes:
     - /sessions
    restart: unless-stopped
version: "2"
